//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteQuaTangOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANGNHAP
    {
        public int Id { get; set; }
        public string TaiKhoang { get; set; }
        public string MatKhau { get; set; }
        public string Email { get; set; }
    }
}
