//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteQuaTangOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public HOADON()
        {
            this.CTHDs = new HashSet<CTHD>();
        }
    
        public int MaHoaDon { get; set; }
        public string TenKhachHang { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
        public string Email { get; set; }
        public string NoiDung { get; set; }
        public int TrangThai { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
    
        public virtual ICollection<CTHD> CTHDs { get; set; }
    }
}
