//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteQuaTangOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public SANPHAM()
        {
            this.CT_PHIEUNHAP = new HashSet<CT_PHIEUNHAP>();
            this.CTHDs = new HashSet<CTHD>();
        }
    
        public string MaSanPham { get; set; }
        
        public string TenSanPham { get; set; }
        public string NhaSanXuat { get; set; }
        public string MaLoaiSanPham { get; set; }
        public string UrlHinhAnh { get; set; }
        public string MoTa { get; set; }
        public int DonGia { get; set; }
        public int SoLuong { get; set; }
        public int SoLuotMua { get; set; }
    
        public virtual ICollection<CT_PHIEUNHAP> CT_PHIEUNHAP { get; set; }
        public virtual ICollection<CTHD> CTHDs { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
    }
}
