//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteQuaTangOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TINTUC
    {
        public int MaTinTuc { get; set; }
        public string TieuDe { get; set; }
        public string MoTa { get; set; }
        public string UrlHinhAnh { get; set; }
        public string NoiDung { get; set; }
        public string TacGia { get; set; }
        public System.DateTime NgayDang { get; set; }
        public int SoLuotxem { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
    }
}
